version: "3.6"
services:
  cassandra:
    build: .
    image: "cassandra:latest"
    ports:
      - 9042:9042
    network_mode: "host"
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
      - /home/nineleaps/myvol1:/var/lib/cassandra
      
    command: "sh /cassandra-init.sh"
    
    restart: always
    
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_HOST: localhost
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CREATE_TOPICS: "Kafka_Order_test3"
    depends_on:
      - zookeeper
    command: [start-kafka.sh]
    network_mode: "host"
    restart: on-failure
    
 
  
  nineleaps-registry:
    build:
      context: .
      dockerfile: /home/nineleaps/eclipse-workspace/POC2/nineleaps-registry/Dockerfile
    image: apiregistry:latest
    ports:
      - "8761:8761"
    restart: on-failure
    
  gateway:
    build:
      context: .
      dockerfile: /home/nineleaps/eclipse-workspace/POC2/nineleaps-apigateway/Dockerfile
    image: apigateway:latest
    ports:
      - "8765:8765"
    links:
      - nineleaps-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://nineleaps-registry:8761/eureka
    restart: always
     
  order:
    build: 
      context: .
      dockerfile: /home/nineleaps/Documents/POC/Order/EcommercePOC/Dockerfile
    image: orderservice:latest
    ports:
      - "8080:8080"
    network_mode: "host"
    depends_on:
       - cassandra
       - gateway
       - kafka
    restart: always
    
  product:
    build:
      context: .
      dockerfile: /home/nineleaps/Documents/POC/Product/ProductService/Dockerfile
    image: productservice:latest
    ports:
      - "8083:8083"
    network_mode: "host"
    depends_on: 
        - cassandra
        - gateway
    environment:
        - JAVA_OPTS= -DEUREKA_SERVER=http://nineleaps-registry:8761/eureka -DKAFKA_SERVER=//localhost:9092 
      
    restart: always
   
  supplier:
    build:
      context: .
      dockerfile: /home/nineleaps/Documents/POC/Supplier/SupplierService/Dockerfile
    image: supplierservice:latest
    ports:
      - "8082:8082"
    network_mode: "host"
    depends_on: 
         - cassandra
         - gateway
         - kafka
    environment:
         - JAVA_OPTS= -DEUREKA_SERVER=http://nineleaps-registry:8761/eureka -DKAFKA_SERVER=//localhost:9092  
   
    env_file:
     - ./my-env.txt
    restart: always
     
    
 